name: Java CI with Maven

on:
  push:
    branches:
      - main # Déclenche l'action sur les pushes vers la branche principale
  pull_request:
    branches:
      - main # Déclenche l'action lors d'une pull request vers la branche principale

jobs:
  build:
    runs-on: ubuntu-latest # Utilise une machine Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Récupère le code source du dépôt

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17" # Utilise JDK 17
          distribution: "openjdk" # Utilise la distribution OpenJDK, qui est largement supportée

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository # Cache le répertoire local de Maven pour accélérer les builds futurs
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} # Utilise le hash de pom.xml pour déterminer si le cache doit être mis à jour
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests # Exécute le build Maven sans tests
